motd:
  useFavicon: true  # Sync with favicon?
  useMaxPlayers: true # Sync with playerCount/MaxplayerCount?
  useMotd: true  # Sync with MOTD?
  useSample: true # Sync with Sample?
  remote:
    use: true  # Do u want use this plugin?
    updateTime: 5  # How long will it take to be updated?
    server:  # Remote Server Info.
      IP: 'mc.hypixel.net'  # Remote Server IP Adress
      Port: 25565  # Remote Server Port
    proxy:  # Proxy Settings
      use: false  # Do u want use Proxy?
      server:  # Proxy Settings
        IP: '188.166.34.137'  # Proxy IP Adress
        Port: 9000  # Proxy Port
        ProxyType: SOCKS  # Proxy Type (SOCKS,HTTP)